version: '3.4'
services:
  devpage_frontend:
    build: ../
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ../
        target: /app

  backend:
    build: ../../../Backend
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: backendData
        target: /app/userData

volumes:
  backendData:
