version: '3.4'
services:
  devpage_frontend:
    build: ../
    container_name: devpage_frontend
    ports:
      - "8080:8080"


  backend:
    build: ../../../Backend
    container_name: api_backend
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: backendData
        target: /app/userData

volumes:
  backendData:
